### ISSUE TITLE
ValueError: day is out of range for month while importing dob violations

### ISSUE THREAD

**Issue by aepyornis** [aepyornis/nyc-db#50]
```
OrderedDict([('isndobbisviol', '129467'), ('boro', '1'), ('bin', '1014006'), ('block', '00769'), ('lot', '00068'), ('iss
uedate', '19910606'), ('violationtypecode', 'Z'), ('violationnumber', 'MTF2LE'), ('housenumber', '194'), ('street', '8 AVENUE'), ('dispositiondate', '1
9940231'), ('dispositioncomments', ''), ('devicenumber', ''), ('description', ''), ('ecbnumber', ''), ('number', 'V*060691ZMTF2LE'), ('violationcategor
y', 'V*-DOB VIOLATION - DISMISSED'), ('violationtype', 'Z-ZONING'), ('bbl', '1007690068')])
```

```
Traceback (most recent call last):
  File "/home/nycdb/.local/bin/nycdb", line 11, in <module>
    load_entry_point('nycdb==0.1.12', 'console_scripts', 'nycdb')()
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/cli.py", line 102, in main
    dispatch(args)
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/cli.py", line 93, in dispatch
    Dataset(args.load, args=args).db_import()
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/dataset.py", line 61, in db_import
    self.import_schema(schema)
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/dataset.py", line 97, in import_schema
    batch = list(itertools.islice(rows, 0, BATCH_SIZE))
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/typecast.py", line 144, in cast_rows
    yield self.cast_row(row)
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/typecast.py", line 155, in cast_row
    d[column] = self.cast[column.lower()](val)
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/typecast.py", line 180, in <lambda>
    d[k] = lambda x: date(x)
  File "/home/nycdb/.local/lib/python3.6/site-packages/nycdb/typecast.py", line 85, in date
    date = datetime.datetime.strptime(x, '%Y%m%d')
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 528, in _strptime
    datetime_date(year, 1, 1).toordinal() + 1
ValueError: day is out of range for month
```

**Comment by aepyornis** [comment]
resolved by  a800863
